version: '3.8'

services:
  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: prometheus-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - prometheus-network

  # Backend API
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: prometheus-server
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      MONGODB_URI: ${MONGODB_URI}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: 7d
    depends_on:
      - redis
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - prometheus-network

  # Frontend Client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: prometheus-client
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:5000
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - prometheus-network

  # AI Engine (Python)
  ai-engine:
    build:
      context: ./ai-engine
      dockerfile: Dockerfile
    container_name: prometheus-ai
    ports:
      - "8000:8000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
    volumes:
      - ./ai-engine:/app
    networks:
      - prometheus-network

volumes:
  redis_data:

networks:
  prometheus-network:
    driver: bridge
